version: '3'

services:
  dhcp:
    image: sirferdek/isc-dhcp-server
    container_name: dhcp
    restart: always
    network_mode: "host"
    volumes:
      - ./vldhcp:/var/lib/dhcp
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    command: ens18

